apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tap-go-web-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tap-go-web-app
    #apps.tanzu.vmware.com/has-tests: true
  namespace: golang
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "2"
  source:
    git:
      url: https://github.com/fabianbrash/go-api2.git
      ref:
        branch: main
